name: Create StreamDeck Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build

    - name: Pack
      uses: neilenns/streamdeck-cli-pack@v1

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          com.ryder.deadlocktracker.streamDeckPlugin

    #- name: Save packaged plugin
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: Deadlock Tracker
    #    path: |
    #      com.ryder.deadlocktracker.streamDeckPlugin
